### DISCUSSION TITLE
Query regarding configuration of a file

### DISCUSSION THREAD

**Discussion by JacobYiu** [crytic/echidna#1237] [Q&A]
Hi, I currently have 2 contracts
```solidity
// SPDX-License-Identifier: UNLICENSED

pragma solidity >=0.5.0 <0.9.0;

contract insecureRandomness   
{
    uint private _lastBlockNumber;
    address randomGeneratorAddress;
    constructor(){
        randomGeneratorAddress = address(this);
    }

    function generateRandomNumber() public returns(uint)
    {
        uint blockNumber = block.number;
        require(blockNumber >_lastBlockNumber, "Unable to generate a random number because someone has already done so. Try again");
        uint randomNum = uint(blockhash(blockNumber)) % 100 + 1;
        _lastBlockNumber = blockNumber;
        return randomNum;
    }

    // Echidna invariant to check that _lastBlockNumber is never ahead of the current block number
    function echidna_test_block_number() public view returns (bool) {
        return _lastBlockNumber <= block.number;
    }
}
```

```solidity
contract Attack {
    insecureRandomness public insecure;
    
    constructor(address _insecureAddress) {
        insecure = insecureRandomness(_insecureAddress);
    }

    // Mock predict function for illustrating purposes
    function predictNextRandom() private view returns (uint) {
        return uint(blockhash(block.number - 1)) % 100 + 1;
    }
    
    // Attempt to call generateRandomNumber and expect a specific result
    // This is theoretical and highly simplified for illustrative purposes
    function echidna_test_predictability() public returns (bool) {
        uint predicted = predictNextRandom();
        uint generated = insecure.generateRandomNumber();
        return predicted != generated; // Invariant fails if we can predict the outcome
    }
}
```

How would I configure a yaml file for this? 
Because I am currently facing an issue in doing so. My goal is to deploy both contracts where the Attack contract has a reference to the insecureRandomness contract, but I keep getting this error stating that echidna: Constructor arguments are required: [("_insecureAddress",address)]

# This is my current yaml file 
```yaml
contractNames: # Correct field to specify contract names
  - "insecureRandomness"
  - "Attack"
deploy:
  insecureRandomness:
    args: [] # No args needed for its constructor
    // Save the address in a variable to use for the Attack contract
    save: "insecureRandomnessAddress" 
  Attack:
    args:
      - "${insecureRandomnessAddress}" # Use the saved address
properties:
  - contract: insecureRandomness
    name: "echidna_test_block_number"
  - contract: Attack
    name: "echidna_test_predictability"
testLimit: 1000
coverage: true

```
